account/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'account_info/', views.account_info, name='account_info'),
    url(r'address/', views.address, name='address'),
    url(r'personal_info/', views.personal_info, name='personal_info'),
    url(r'confirmation/', views.confirmation, name='confirmation'),
    
    url(r'setup_facebook_login/', views.setup_facebook_login, name='setup_facebook_login'),
    
    #url(r'new_facebook_account/', views.new_facebook_account, name='new_facebook_account'),
    
    url(r'create_group/', views.create_group, name='create_group'),
    url(r'edit_group/([0-9]*)', views.edit_group, name='edit_group'),
    url(r'delete_group/', views.delete_group, name='delete_group'),
    
    url(r'account/', views.account, name='account'),
    
    url(r'upload_image/', views.upload_image, name='upload_image'),
    url(r'view/([0-9]*)', views.view, name='view'),
    url(r'unsubscribe/', views.unsubscribe, name='unsubscribe'),
    url(r'unsubscribe_confirm/', views.unsubscribe_confirm, name='unsubscribe_confirm'),
    
]

alerts/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'alerts/', views.alerts, name='alerts'),
    
]

pm/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'messages/([0-9]*)', views.messages, name='messages'),
    url(r'message_list', views.message_list, name='message_list'),
]

relationships/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'add-friend/', views.add_friend, name='add-friend'),
    url(r'create-guest/', views.create_guest, name='create-guest'),
    url(r'remove-friend/', views.remove_friend, name='remove-friend'),
    url(r'add-guest-friend/', views.add_guest_friend, name='add-guest-friend'),
    url(r'remove-guest-friend/', views.remove_guest_friend, name='remove-guest-friend'),
    url(r'relationships/', views.relationships, name='relationships'),
    url(r'participant_search/', views.participant_search, name='participant_search'),
    url(r'email_search/', views.email_search, name='email_search'),
    
    url(r'friend_suggestions/', views.friend_suggestions, name='friend_suggestions'),
    
    url(r'^join_group/', views.join_group, name='join_group'),
    url(r'^unjoin_group/', views.unjoin_group, name='unjoin_group'),
    url(r'^add_to_group/', views.add_to_group, name='add_to_group'),
    url(r'^remove_from_group/', views.remove_from_group, name='remove_from_group'),
    url(r'^add_group_members/', views.add_group_members, name='add_group_members'),
]

villagebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'main.views.custom_404'
handler500 = 'main.views.custom_500'
handler403 = 'main.views.custom_403'

urlpatterns = [
    #direct links to views
    url(r'^login/', 'main.views.login_view', name='login'),
    url(r'^facebook_test/', 'main.views.facebook_test', name='facebook_test'),
    url(r'^facebook_login_test/', 'main.views.facebook_login_test', name='facebook_login_test'),
    url(r'^logout/', 'main.views.logout_view', name='logout'),
    url(r'^hide_me/', 'main.views.hide_me', name='hide_me'),
    url(r'^request_reset_password/', 'main.views.request_reset_password', name='request_reset_password'),
    url(r'^reset_password/([a-zA-Z0-9]*)', 'main.views.reset_password', name='reset_password'),
    url(r'^info$', 'main.views.info', name='info'),
    
    #note: pages in main do not have a namespace 
    url(r'^$', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^relationships/', include('relationships.urls', namespace="relationships")),
    url(r'^alerts/', include('alerts.urls', namespace="alerts")),
    url(r'^requests/', include('requests.urls', namespace="requests")),
    url(r'^pm/', include('pm.urls', namespace="pm")),
    url(r'^sharing/', include('sharing.urls', namespace="sharing")),
    
    
]

alerts/models.py
from django.db import models
from account.models import Participant

class Event(models.Model):
    EVENT_TYPE_CHOICES = (
      ("add friend", "add friend"),
    )
    affected_participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    event_type = models.CharField(max_length=30, choices=EVENT_TYPE_CHOICES, db_index=True)
    viewed = models.BooleanField(db_index=True)
    active = models.BooleanField(db_index=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    event_data = models.TextField(blank=True, null=True)
    more_data = models.TextField(blank=True, null=True)

alerts/views.py
import json
import time

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from account.models import Participant
from .helpers import *




@login_required
@csrf_exempt
def alerts(request):
    user = request.user
    currentParticipant = Participant.objects.get(user=user, type='member')
    display = False
    if request.method == "POST":
        action = request.POST.get("action")
        if action == 'reset_count':
            time.sleep(10)
            resetAlertCount(currentParticipant)
        if action == 'delete_alert':
            deleteAlert(request.POST.get("alert_id"))
            display = True
    alerts = getAlerts(currentParticipant)
    context = {
            'alerts' : alerts['alerts'],
            'alertCount' : alerts['count'],
        }
    html = render_to_string('alerts/alerts.html', context)
    data = {
        'html' : html,
        'count' : alerts['count'],
        'display' : display,
    }
    return HttpResponse(json.dumps(data), content_type = "application/json")

villagebuilder/templates/core/blocks/alerts.html
{% if messages %}
	{% for message in messages %}
	    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
	        <div class="alert alert-dismissible alert-danger">
			    <button type="button" class="close" data-dismiss="alert">X</button>
			    <p>{{ message }}</p>
			</div>
	    {% endif %}
	    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
	        <div class="alert alert-dismissible alert-warning">
			    <button type="button" class="close" data-dismiss="alert">X</button>
			    <p>{{ message }}</p>
			</div>
	    {% endif %}
	    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
	        <div class="alert alert-dismissible alert-success">
			    <button type="button" class="close" data-dismiss="alert">X</button>
			    <p>{{ message }}</p>
			</div>
	    {% endif %}
	{% endfor %}
{% endif %}

villagebuilder/templates/core/blocks/formgroup.html
{% load app_filters %}
{% load widget_tweaks %}

{% if field|field_type == 'booleanfield' %}
    {{ field.errors }}
    <div class="checkbox">
      <label>
        {{field}} {{ field.label }}
      </label>
    </div>
{% else %}
	<div class="form-group">
	    {{ field.errors }}
	    {{ field|label_with_classes:"control-label" }}
	    {{ field|attr:"class:form-control" }}
	    <span class="help-block">{{ field.help_text }}</span>
	</div>
{% endif %}

villagebuilder/templates/core/blocks/login_window_1.html
{% load staticfiles %}

<img src="{% static 'img/vb-v-large.png' %}" alt="VillageBuilder" width="300" height="300" /> 
<div class="text-muted" style="font-weight:bold;font-size:35px;letter-spacing:-2px;">
	welcome to the real sharing economy
</div>

villagebuilder/templates/core/blocks/login_window_2.html
{% load app_filters %}
{% load widget_tweaks %}

<form action="{% url 'account:account_info' %}" method="post" id="main-form">
    {% csrf_token %}
    <div style="text-align:center;">
   		<h3>Create Your Free Account</h3>
   	</div>
    <div style="width:420px;margin:0 auto;border-top:1px solid #EC7621; padding-top:10px;overflow:hidden;padding-right:2px;">
        <div class="form-group">
            {{ createAccountForm.email|label_with_classes:"control-label" }} 
            {{ createAccountForm.email|attr:"class:form-control" }}
        </div>
	    <div style="width:200px;margin-right:18px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.first_name|label_with_classes:"control-label" }} 
		            {{ createAccountForm.first_name|attr:"class:form-control" }}
		            <a href="#" data-toggle="modal" data-target="#name-privacy-modal"> 
		                <i class="fa fa-question-circle"></i> Do you need my name?
	                </a>
	        </div>
	    </div>
	    <div style="width:200px;float:left;">
			<div class="form-group">
			 	{{ createAccountForm.last_name|label_with_classes:"control-label" }} 
			 	{{ createAccountForm.last_name|attr:"class:form-control" }}
			</div>
	    </div>
	    <div style="width:200px;margin-right:18px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.password|label_with_classes:"control-label" }} 
		            {{ createAccountForm.password|attr:"class:form-control" }}
		            <span class="text-muted">minimum 8 characters</span>
	        </div>
	    </div>
	    <div style=width:200px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.resubmit_password|label_with_classes:"control-label" }} 
		            {{ createAccountForm.resubmit_password|attr:"class:form-control" }}
	        </div>
	    </div>
		<input type="hidden" name="redirect-url" value="" />
	</div>
	<div style="text-align: right;width:420px;margin:0 auto;">
	    <button type="submit" class="btn btn-success">
	    	Next Step <i class="fa fa-angle-double-right"></i>
	    </button>
	</div>
	
</form>

villagebuilder/templates/core/blocks/login_window_3.html
{% load staticfiles %}

<style>
#person1 {
	position:absolute;
	left: 200px;
	top: 140px;
}
#person2 {
	position:absolute;
	left: 20px;
	top: 210px;
	opacity: 0;
}
#person3 {
	position:absolute;
	left: 390px;
	top: 215px;
	opacity: 0;
}
#arrow1 {
	position:absolute;
	left: 150px;
	top: 260px;
	opacity: 0;
}
#arrow2 {
	position:absolute;
	left: 345px;
	top: 260px;
	opacity: 0;
}

#item1 {
	position:absolute;
	left: 300px;
	top: 150px;
}
#item2 {
	position:absolute;
	left: 300px;
	top: 150px;
}
#item3 {
	position:absolute;
	left: 300px;
	top: 150px;
}
#item4 {
	position:absolute;
	left: 300px;
	top: 150px;
}
#item5 {
	position:absolute;
	left: 300px;
	top: 150px;
}

#item6 {
	position:absolute;
	left: 412px;
	top: 37px;
}
#item7 {
	position:absolute;
	left: 487px;
	top: 37px;
}
#item8 {
	position:absolute;
	left: 562px;
	top: 37px;
}
#item9 {
	position:absolute;
	left: 37px;
	top: 112px;
}
#item10 {
	position:absolute;
	left: 112px;
	top: 112px;
}
#item11 {
	position:absolute;
	left: 187px;
	top: 112px;
}
#item12 {
	position:absolute;
	left: 262px;
	top: 112px;
}
#item13 {
	position:absolute;
	left: 337px;
	top: 112px;
}
#item14 {
	position:absolute;
	left: 412px;
	top: 112px;
}
#item15 {
	position:absolute;
	left: 487px;
	top: 112px;
}
#item16 {
	position:absolute;
	left: 562px;
	top: 112px;
}

</style>

<img id="person1" src="{% static 'img/slideshow/person1.png' %}" alt="VillageBuilder" width="200" height="200" /> 
<img id="person2" src="{% static 'img/slideshow/person2.png' %}" alt="VillageBuilder" width="120" height="120" /> 
<img id="person3" src="{% static 'img/slideshow/person3.png' %}" alt="VillageBuilder" width="190" height="115" /> 
<img id="arrow1" src="{% static 'img/slideshow/arrow1.png' %}" alt="VillageBuilder" width="50" height="20" /> 
<img id="arrow2" src="{% static 'img/slideshow/arrow2.png' %}" alt="VillageBuilder" width="50" height="20" /> 

<img id="item1" src="{% static 'img/slideshow/item1.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item2" src="{% static 'img/slideshow/item2.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item3" src="{% static 'img/slideshow/item3.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item4" src="{% static 'img/slideshow/item4.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item5" src="{% static 'img/slideshow/item5.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item6" src="{% static 'img/slideshow/item6.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item7" src="{% static 'img/slideshow/item7.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item8" src="{% static 'img/slideshow/item8.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item9" src="{% static 'img/slideshow/item9.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item10" src="{% static 'img/slideshow/item10.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item11" src="{% static 'img/slideshow/item11.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item12" src="{% static 'img/slideshow/item12.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item13" src="{% static 'img/slideshow/item13.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item14" src="{% static 'img/slideshow/item14.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item15" src="{% static 'img/slideshow/item15.png' %}" alt="VillageBuilder" width="0" height="0" /> 
<img id="item16" src="{% static 'img/slideshow/item16.png' %}" alt="VillageBuilder" width="0" height="0" /> 





<div id="panel2-text" style="opacity:0;" class="slideshow-text">
	Have power tools gathering dust?  Hanging on to that old stroller just in case?  
	VillageBuilder lets you share those extra items with friends and neighbors.
</div>



villagebuilder/templates/core/blocks/login_window_6.html
{% load app_filters %}
{% load widget_tweaks %}

<style>
#panel6-text {
	opacity: 0;
}
</style>



<form action="{% url 'account:account_info' %}" method="post" id="main-form">
    {% csrf_token %}
    <div style="width:420px;margin:0 auto;overflow:hidden;padding:10px 2px 10px 0;">
        <div class="form-group">
            {{ createAccountForm.email|attr:"class:form-control"|attr:"placeholder:Email" }}
        </div>
        <div class="text-danger form-errors">{{ createAccountForm.email.errors }}</div>
	    <div style="width:200px;margin-right:18px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.first_name|attr:"class:form-control"|attr:"placeholder:first name" }}
	        </div>
	        <div class="text-danger form-errors">{{ createAccountForm.first_name.errors }}</div>
	    </div>
	    <div style="width:200px;float:left;">
			<div class="form-group">
			 	{{ createAccountForm.last_name|attr:"class:form-control"|attr:"placeholder:last name" }}
			</div>
			<div class="text-danger form-errors">{{ createAccountForm.last_name.errors }}</div>
	    </div>
	    <div style="width:200px;margin-right:18px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.password|attr:"class:form-control"|attr:"placeholder:password" }}
		            <span class="text-muted">minimum 8 characters</span>
	        </div>
	        <div class="text-danger form-errors">{{ createAccountForm.password.errors }}</div>
	    </div>
	    <div style=width:200px;float:left;">
	        <div class="form-group">
		            {{ createAccountForm.resubmit_password|attr:"class:form-control"|attr:"placeholder:reenter password" }}
	        </div>
	        <div class="text-danger form-errors">{{ createAccountForm.resubmit_password.errors }}</div>
	    </div>
		<input type="hidden" name="redirect-url" value="" />
		<div style="text-align: right;clear:both;">
		    <button type="submit" class="btn btn-success btn-block">
		    	Continue <i class="fa fa-angle-double-right"></i>
		    </button>
		</div>
		
		<div style="height:1px; background-color:black; text-align:center;margin: 25px 0;clear:both;">
		    <span style="background-color: white; position: relative; top: -0.6em;">
		        OR
		    </span>
		</div>
		
		
		<button class="btn btn-primary btn-block facebook-login-btn" type="button">
			<i class="fa fa-facebook-official"></i> Continue with Facebook
		</button>
	</div>
	<div style="padding-top: 30px;" id="panel6-text" class="slideshow-text">
		Own less and have more.  Create your free account today.
	</div>
	
</form>

villagebuilder/templates/core/blocks/participantgroup.html
	    
<div class="list-group-item participant-block" >
	<div style="float: right;">
	
	    {% include 'core/blocks/participantgroup_actions.html' %}
		
   	</div>
    <div style="float: left;padding-right:10px;">
    	<img src="{{ participant.thumb }}" alt="my alt" width="40" height="40" />
   	</div>
    <a href="{% url 'account:view' participant.id %}" class="participant-name-link">{{ participant.name }}</a><br>
    {{ participant.display_address }}
</div>

				

villagebuilder/templates/core/blocks/participantgroup_actions.html


{% if participant.relationship != RelationshipTypes.SELF %}
	<div class="btn-group">
		<a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
		<ul class="dropdown-menu dropdown-menu-right widen" style="padding: 5px 10px;">
		    {% if participant.relationship == RelationshipTypes.FRIENDS %}
				<li><i class="fa fa-check"></i> You are Friends</li>
				<li class="hcenter-content">
					<form method="POST" action="{% url 'relationships:remove-friend' %}" id="remove-friend-form-{{participant.id}}">
						{% csrf_token %}
						<input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
						<input type="hidden" name="friend-id" value="{{participant.id}}" />
						<button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Unfriend</button>
					</form>
				</li>
			{% endif %}
			{% if participant.relationship == RelationshipTypes.NOT_FRIENDS %}
	    	<div class="btn-group">
			    <li class="hcenter-content">
			        <form method="POST" action="{% url 'relationships:add-friend' %}" id="add-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="friend-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Add as friend</button>
			        </form>
		        </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.REQUEST_SENT %}
			    <li><i class="fa fa-check"></i> Request Sent (awaiting confirmation)</li>
			    <li class="hcenter-content">
			        <form method="POST" action="{% url 'relationships:remove-friend' %}" id="remove-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="friend-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Cancel Request</button>
			        </form>
		        </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.REQUEST_RECEIVED %}
			    <li><i class="fa fa-check"></i> Request Received</li>
			    <li class="hcenter-content">
			        <form method="POST" action="{% url 'relationships:add-friend' %}" id="add-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="friend-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Accept Friend Request</button>
			        </form>
			        <form method="POST" action="{% url 'relationships:remove-friend' %}" id="ignore-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="friend-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-warning btn-xs btn-participantgroup">Ignore</button>
			        </form>
		        </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.GUEST_FRIENDS %}
			    <li><i class="fa fa-check"></i> Guest Friends</li>
			    <li class="hcenter-content">
			        <form method="POST" 
			        		action="{% url 'relationships:remove-guest-friend' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="friend-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Unfriend</button>
			        </form>
		        </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.NOT_GUEST_FRIENDS %}
			    <li class="hcenter-content">
			        <form method="POST" 
			        		action="{% url 'relationships:add-guest-friend' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="guest-id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Add as friend</button>
			        </form>
		        </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.GROUP_OWNER %}
			    <li>This is your group.</li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.GROUP_MEMBER %}
			    <li>You belong to this group.</li>
			    <li class="hcenter-content">
				    <form method="POST" 
			        		action="{% url 'relationships:unjoin_group' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="group_id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Unjoin Group</button>
			        </form>
			    </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.NOT_GROUP_MEMBER %}
			    <li class="hcenter-content">
				    <form method="POST" 
			        		action="{% url 'relationships:join_group' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="group_id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Request to Join Group</button>
			        </form>
			    </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.GROUP_MEMBER_REQUESTED %}
			    <li>Membership requested (awaiting approval)</li>
			    <li class="hcenter-content">
				    <form method="POST" 
			        		action="{% url 'relationships:unjoin_group' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="group_id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Cancel Request</button>
			        </form>
			    </li>
			{% endif %}	
			{% if participant.relationship == RelationshipTypes.GROUP_MEMBER_INVITED %}
			    <li>You have been invited by the group owner to join this group.</li>
			    <li class="hcenter-content">
				    <form method="POST" 
			        		action="{% url 'relationships:join_group' %}" 
			        		id="remove-guest-friend-form-{{participant.id}}">
			            {% csrf_token %}
			            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
			            <input type="hidden" name="group_id" value="{{participant.id}}" />
			            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Join Group</button>
			        </form>
			    </li>
			{% endif %}	

			{% for group_relationship in participant.group_relationships %}
			    {% if group_relationship.relationship == RelationshipTypes.GROUP_MEMBER %}
					<li class="divider"></li>
					<li><i class="fa fa-check"></i> Member of {{ group_relationship.name }}</li>
					<li class="hcenter-content">
					    <form method="POST" 
				        		action="{% url 'relationships:remove_from_group' %}" 
				        		id="remove-guest-friend-form-{{participant.id}}">
				            {% csrf_token %}
				            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
				            <input type="hidden" name="member-id" value="{{participant.id}}" />
				            <input type="hidden" name="group-id" value="{{group_relationship.id}}" />
				            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Remove from Group</button>
				        </form>
				    </li>
				{% endif %}	
				{% if group_relationship.relationship == RelationshipTypes.NOT_GROUP_MEMBER %}
					<li class="divider"></li>
					<li>Not a member of {{ group_relationship.name }}</li>
					<li class="hcenter-content">
					    <form method="POST" 
				        		action="{% url 'relationships:add_to_group' %}" 
				        		id="remove-guest-friend-form-{{participant.id}}">
				            {% csrf_token %}
				            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
				            <input type="hidden" name="member-id" value="{{participant.id}}" />
				            <input type="hidden" name="group-id" value="{{group_relationship.id}}" />
				            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Invite to Join</button>
				        </form>
				    </li>
				{% endif %}	
				{% if group_relationship.relationship == RelationshipTypes.GROUP_MEMBER_REQUESTED %}
					<li class="divider"></li>
					<li>Wants to join {{ group_relationship.name }}</li>
					<li class="hcenter-content">
					    <form method="POST" 
				        		action="{% url 'relationships:add_to_group' %}" 
				        		id="remove-guest-friend-form-{{participant.id}}">
				            {% csrf_token %}
				            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
				            <input type="hidden" name="member-id" value="{{participant.id}}" />
				            <input type="hidden" name="group-id" value="{{group_relationship.id}}" />
				            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Accept Request</button>
				            <button type="button" class="btn btn-warning btn-xs btn-participantgroup">Ignore</button>
				        </form>
				    </li>
				{% endif %}	
				{% if group_relationship.relationship == RelationshipTypes.GROUP_MEMBER_INVITED %}
					<li class="divider"></li>
					<li>You invited to join {{ group_relationship.name }}</li>
					<li class="hcenter-content">
					    <form method="POST" 
				        		action="{% url 'relationships:remove_from_group' %}" 
				        		id="remove-guest-friend-form-{{participant.id}}">
				            {% csrf_token %}
				            <input type="hidden" name="redirect" value="{{request.build_absolute_uri}}" />
				            <input type="hidden" name="member-id" value="{{participant.id}}" />
				            <input type="hidden" name="group-id" value="{{group_relationship.id}}" />
				            <button type="submit" class="btn btn-primary btn-xs btn-participantgroup">Cancel Invitation</button>
				        </form>
				    </li>
				{% endif %}	
			{% endfor %}
		</ul>
	</div>
{% endif %}