account/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'account_info/', views.account_info, name='account_info'),
    url(r'address/', views.address, name='address'),
    url(r'personal_info/', views.personal_info, name='personal_info'),
    url(r'confirmation/', views.confirmation, name='confirmation'),
    
    url(r'setup_facebook_login/', views.setup_facebook_login, name='setup_facebook_login'),
    
    #url(r'new_facebook_account/', views.new_facebook_account, name='new_facebook_account'),
    
    url(r'create_group/', views.create_group, name='create_group'),
    url(r'edit_group/([0-9]*)', views.edit_group, name='edit_group'),
    url(r'delete_group/', views.delete_group, name='delete_group'),
    
    url(r'account/', views.account, name='account'),
    
    url(r'upload_image/', views.upload_image, name='upload_image'),
    url(r'view/([0-9]*)', views.view, name='view'),
    url(r'unsubscribe/', views.unsubscribe, name='unsubscribe'),
    url(r'unsubscribe_confirm/', views.unsubscribe_confirm, name='unsubscribe_confirm'),
    
]

pm/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'messages/([0-9]*)', views.messages, name='messages'),
    url(r'message_list', views.message_list, name='message_list'),
]

relationships/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'add-friend/', views.add_friend, name='add-friend'),
    url(r'create-guest/', views.create_guest, name='create-guest'),
    url(r'remove-friend/', views.remove_friend, name='remove-friend'),
    url(r'add-guest-friend/', views.add_guest_friend, name='add-guest-friend'),
    url(r'remove-guest-friend/', views.remove_guest_friend, name='remove-guest-friend'),
    url(r'relationships/', views.relationships, name='relationships'),
    url(r'participant_search/', views.participant_search, name='participant_search'),
    url(r'email_search/', views.email_search, name='email_search'),
    
    url(r'friend_suggestions/', views.friend_suggestions, name='friend_suggestions'),
    
    url(r'^join_group/', views.join_group, name='join_group'),
    url(r'^unjoin_group/', views.unjoin_group, name='unjoin_group'),
    url(r'^add_to_group/', views.add_to_group, name='add_to_group'),
    url(r'^remove_from_group/', views.remove_from_group, name='remove_from_group'),
    url(r'^add_group_members/', views.add_group_members, name='add_group_members'),
]

villagebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'main.views.custom_404'
handler500 = 'main.views.custom_500'
handler403 = 'main.views.custom_403'

urlpatterns = [
    #direct links to views
    url(r'^login/', 'main.views.login_view', name='login'),
    url(r'^facebook_test/', 'main.views.facebook_test', name='facebook_test'),
    url(r'^facebook_login_test/', 'main.views.facebook_login_test', name='facebook_login_test'),
    url(r'^logout/', 'main.views.logout_view', name='logout'),
    url(r'^hide_me/', 'main.views.hide_me', name='hide_me'),
    url(r'^request_reset_password/', 'main.views.request_reset_password', name='request_reset_password'),
    url(r'^reset_password/([a-zA-Z0-9]*)', 'main.views.reset_password', name='reset_password'),
    url(r'^info$', 'main.views.info', name='info'),
    
    #note: pages in main do not have a namespace 
    url(r'^$', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^relationships/', include('relationships.urls', namespace="relationships")),
    url(r'^alerts/', include('alerts.urls', namespace="alerts")),
    url(r'^requests/', include('requests.urls', namespace="requests")),
    url(r'^pm/', include('pm.urls', namespace="pm")),
    url(r'^sharing/', include('sharing.urls', namespace="sharing")),
    
    
]

account/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.conf import settings

import string
import random

def createRandomString(length):
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(length))


# User Model:
# username *
# first_name
# last_name
# email
# password *
# groups
# user_permissions
# is_staff
# is_active
# is_superuser
# last_login (auto)
# date_joined (auto)
# ---
# get_username()
# is_authenticated()
# get_full_name()
# get_short_name()
# set_password(pw)
# check_password(pw)
# email_user(subject, message, from_email)


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    facebook_id = models.CharField(max_length=120, blank=True, null=True)


class Participant(models.Model):
    PARTICIPANT_TYPES = (
        ('member', 'member'),
        ('guest', 'guest'),
        ('group', 'group'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    type = models.CharField(max_length=6, choices=PARTICIPANT_TYPES, db_index=True)
    
    def __unicode__(self):
         return self.get_name()
    
    def get_name(self, length='full'):
        if self.type == 'group':
            return self.group.title
        else:
            if length=='full':
                return self.user.get_full_name()
            else:
                return self.user.get_short_name()
    
    def get_first_name(self):
        if self.type == 'group':
            return self.group.title
        else:
            return self.user.get_short_name()
        
            
    def get_email(self):
        if self.type == 'group' and self.group.email:
            return self.group.email
        else:
            return self.user.email
        
    def get_image(self):
        if self.type == 'member' and self.member.image:
            return '/static/uploads/user_pics/' + self.member.image
        if self.type == 'group' and self.group.image:
            return '/static/uploads/user_pics/' + self.group.image
        return '/static/img/generic-user.png'
        
    def get_thumb(self):
        if self.type == 'member' and self.member.thumb:
            return '/static/uploads/user_pics/' + self.member.thumb
        if self.type == 'group' and self.group.thumb:
            return '/static/uploads/user_pics/' + self.group.thumb
        else:
            return '/static/img/generic-user.png'
        
    def get_display_address(self):
        if self.type == 'guest':
            return '(guest account)'
        if self.type == 'group':
            return 'Group created by ' + self.group.owner.participant.get_name()
        if self.type == 'member':
            return self.member.get_display_address()
        
    def get_display_address_long(self):
        if self.type == 'guest':
            return '(guest account)'
        if self.type == 'group':
            return self.group.get_display_address_long()
        if self.type == 'member':
            return self.member.get_display_address_long()

        
    def get_public(self):
        result = {
            'id' : self.id,
            'type' : self.type,
            'name' : self.get_name(),
            'display_address' : self.get_display_address(),
            'image' : self.get_image(),
            'thumb' : self.get_thumb(),
        }
        if self.type == 'group':
            result['owner'] = self.group.owner.participant.get_public()
        return result
    
    def get_private(self, currentUser):
        result = self.get_public()
        result['email'] = ''
        return result
        


# need non-auto pk field so that it can be set to the same value as participant
class Member(models.Model):
    id = models.IntegerField(primary_key=True)
    participant = models.OneToOneField('Participant', on_delete=models.CASCADE)
    full_address = models.CharField(max_length=600)
    # address1 = models.CharField(max_length=50, blank=True, null=True)
    # address2 = models.CharField(max_length=50, blank=True, null=True)
    street = models.CharField(max_length=60, blank=True, null=True)
    neighborhood = models.CharField(max_length=60, blank=True, null=True)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=2, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    # phone_number = models.CharField(max_length=20, blank=True, null=True)
    # phone_type = models.CharField(max_length=20, blank=True, null=True, choices=PHONE_TYPE_CHOICES)
    share_email = models.BooleanField(default=True)
    # share_phone = models.BooleanField()
    share_street = models.BooleanField(default=True)
    
    EMAIL_OFF = 0
    EMAIL_DAILY_DIGEST = 1
    EMAIL_IMMEDIATELY = 2
    EMAIL_CHOICES = (
        (EMAIL_OFF, 'no email'),
        (EMAIL_DAILY_DIGEST, 'daily digest'),
        (EMAIL_IMMEDIATELY, 'immediate'),
    )
    email_friend_requests = models.PositiveSmallIntegerField(default=2, choices=EMAIL_CHOICES)
    email_pm = models.PositiveSmallIntegerField(default=2, choices=EMAIL_CHOICES)
    email_requests = models.PositiveSmallIntegerField(default=2, choices=EMAIL_CHOICES)
    email_request_comments = models.PositiveSmallIntegerField(default=1, choices=EMAIL_CHOICES)
    email_shared_items = models.PositiveSmallIntegerField(default=1, choices=EMAIL_CHOICES)
    last_emailed = models.DateTimeField()
    
    image = models.CharField(max_length=30, blank=True, null=True)
    thumb = models.CharField(max_length=30, blank=True, null=True)
    code = models.CharField(max_length=60, blank=True, null=True)
    unsubscribe_code = models.CharField(max_length=60, blank=True, null=True)  #use get_unsubscribe_code()
    is_admin = models.BooleanField(default=False, db_index=True)
    
    def __unicode__(self):
        return self.participant.get_name()
     
    def get_unsubscribe_code(self):
        if self.unsubscribe_code:
            return self.unsubscribe_code
        else:
            self.unsubscribe_code = createRandomString(60)
            self.save()
            return self.unsubscribe_code
    
    def get_image(self):
        return self.participant.get_image()
    
    def get_thumb(self):
        return self.participant.get_thumb()
    
    def get_name(self):
        return self.participant.get_name()
    
    def get_display_address(self):
        if self.share_street:
            if self.neighborhood:
                return self.street + ' (' + self.neighborhood + ')'
            else:
                return self.street + ' (' + self.city + ')'
        else:
            if self.neighborhood:
                return '(' + self.neighborhood + ')'
            else:
                return '(' + self.city + ')'
            
    def get_display_address_long(self):
        x = []
        if self.share_street:
            x.append(self.street)
        if self.neighborhood:
            x.append(self.neighborhood)
        x.append(self.city)
        if self.state:
            x.append(self.state)
        return ', '.join(x)
        
        

class Guest(models.Model):
    id = models.IntegerField(primary_key=True)
    participant = models.OneToOneField('Participant', on_delete=models.CASCADE)
    code = models.CharField(max_length=60)
    created_by = models.ForeignKey('Member')
    
    def get_image(self):
        return '/static/img/generic-user.png'
    
    def get_thumb(self):
        return '/static/img/generic-user.png'


    
    
class Group(models.Model):
    id = models.IntegerField(primary_key=True)
    participant = models.OneToOneField('Participant', on_delete=models.CASCADE)
    title = models.CharField(max_length=120, db_index=True)
    description = models.TextField(blank=True, null=True)
    neighborhood = models.CharField(max_length=60, blank=True, null=True)
    city = models.CharField(max_length=60, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    email = models.CharField(max_length=120, blank=True, null=True)
    website = models.CharField(max_length=240, blank=True, null=True)
    image = models.CharField(max_length=30, blank=True, null=True)
    thumb = models.CharField(max_length=30, blank=True, null=True)
    owner = models.ForeignKey('Member', on_delete=models.CASCADE)
    private = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    
    def get_display_address_long(self):
        x = []
        if self.neighborhood:
            x.append(self.neighborhood)
        if self.city:
            x.append(self.city)
        if self.state:
            x.append(self.state)
        return ', '.join(x)


        
        



        

account/templates/account_info.html
{% extends "base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block content %}
    {% include "js/account_info.html" %}
    
    <div class="container-fluid">
        {% include "blocks/create-account-header.html" %}
	    </div>
		<div class="row">
			<div class="col-md-6">
				<form action="{{ callback }}" method="post" id="main-form">
				    {% csrf_token %}
				    {{ form.non_field_errors }}
				    {% for field in form %}
				        <div class="form-group">
				            {{ field|label_with_classes:"control-label" }} 
				            {{ field|attr:"class:form-control" }}
			            </div>
			            <div id="form-errors" style="color:red;">{{ field.errors }}</div>
				    {% endfor %}
				    <input type="hidden" name="redirect-url" value="" />
				    <input type="submit" value="Submit" />
				</form>
			</div>
		</div>
	</div>
{% endblock %}

account/templates/account_view.html
{% extends "home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block subcontent %}


	
	<div class="row">
	    <div class="col-sm-2">
    		<img src="{{ account.image }}" alt="" width="250" height="250" style="float:left;">
    	</div>
    	<div class="col-sm-5">
			<h1>{{ account.name }}</h1>
			<p>{{ account.display_address }}</p>
			{% if account.relationship == RelationshipTypes.FRIENDS %}
			    <i class="fa fa-check"></i> You are friends
			{% endif %}
			{% if account.relationship == RelationshipTypes.NOT_FRIENDS %}
			    <button class="btn btn-primary">Add as Friend <i class="fa fa-plus"></i></button>
			{% endif %}
			{% if account.relationship == RelationshipTypes.GROUP_OWNER %}
			    <a href="{% url 'account:edit_group' account.id %}" class="btn btn-primary">Manage Group</a>
			{% endif %}
			{% if account.relationship == RelationshipTypes.NOT_GROUP_MEMBER %}
				<form method="post" action="{% url 'relationships:join_group' %}">
				    {% csrf_token %}
					<input type="hidden" name="redirect" value="{{ request.build_absolute_uri }}" />
					<input type="hidden" name="group-id" value="{{ account.id }}" />
			    	<button type="submit" class="btn btn-primary">Join Group</a>
			    </form>
			{% endif %}
			{% if account.relationship == RelationshipTypes.GROUP_MEMBER_REQUESTED %}
				You have requested membership in this group and are awaiting confirmation from the group owner.<br>
			    <a href="{% url 'account:edit_group' account.id %}" class="btn btn-primary">Cancel Request to Join</a>
			{% endif %}
			{% if account.relationship == RelationshipTypes.GROUP_MEMBER_INVITED %}
				The owner of this group has invited you to join.<br>
			    <a href="{% url 'account:edit_group' account.id %}" class="btn btn-primary">Join Group</a>
			{% endif %}
		</div>
		<div class="col-sm-4 well">
			<h4>Contact Info</h4>
			{% if account.relationship == RelationshipTypes.SELF %}
			    <div class="alert alert-success">
				  Your contact info is only visible to friends.
				</div>
			{% endif %}
			{% if account.type == 'group' %}
			    Owner: {{ account.owner.id }} {{ account.owner.name }}
			{% endif %}
			<dl class="dl dl-3">
				{% if account.email  %}
				   <dt>Email:</dt>
				   <dd>{{ account.email }}</dd>
				{% endif %}
				{% if account.full_address  %}
				   <dt>Full Address:</dt>
				   <dd>{{ account.full_address }}</dd>
				{% endif %}
				{% if account.phone  %}
				   <dt>Phone:</dt>
				   <dd>{{ account.phone }}</dd>
				{% endif %}
			</dl><br>
			<button class="btn btn-primary">Send a Message <i class="fa fa-paper-plane"></i></button>
		</div>
	</div>
    <hr>
    <ul class="nav nav-tabs">
		<li class="active"><a href="#items" data-toggle="tab">Shared Items</a></li>
		{% if account.type == 'member' %}
		    <li><a href="#friends" data-toggle="tab">Friends</a></li>
		{% endif %}
		{% if account.type == 'group' %}
		    <li><a href="#members" data-toggle="tab">Members</a></li>
		{% endif %}
	</ul>
	<div id="myTabContent" class="tab-content">
	  <div class="tab-pane fade active in" id="items">
	    <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
	  </div>
	  <div class="tab-pane fade" id="friends">
	    <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit.</p>
	  </div>
</div>

{% endblock %}	





account/templates/create_group.html
{% extends "home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block subcontent %}

{% include 'modals/upload_tool.html' %}

<script type="text/javascript">

	function updatePageAfterImageUpload(data) {
		console.log(data)
		$('#id_image').val(data.image.file);
		$('#id_thumb').val(data.thumb.file);
		//$(".current-user-pic").attr("src", data.image.path);
		//$("#shared-user-pic").attr("src", data.image.path);
	}
	
	var dataToAccompanyImageUpload = {}
	var imageUploadUrl = '{% url 'account:upload_image' %}'


	$(document).ready(function(){
		

	}); 
</script>

   

	<div class="row">
		<div class="col-md-6">
		    <a href="#" id="user-pic-edit-btn" data-toggle="modal" data-target="#upload-pic-modal">Edit Pic</a>
			<form action="{{ callback }}" method="post" id="main-form">
			    {% csrf_token %}
			    {{ form.non_field_errors }}
			    {% for field in groupForm %}
			        {% if field.label != 'Imagefff' and field.label != 'Thumbfff' %}
				        <div class="form-group">
				            {{ field|label_with_classes:"control-label" }} 
				            {{ field|attr:"class:form-control" }}
			            </div>
			            <div id="form-errors" style="color:red;">{{ field.errors }}</div>
			        {% endif %}
			    {% endfor %}
			    <input type="hidden" name="redirect-url" value="" />
			    <input type="submit" value="Submit" />
			</form>
			
		</div>
	</div>

{% endblock %}

account/templates/edit_group.html
{% extends "home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block subcontent %}
   
	<form action="{{ callback }}" method="post" id="main-form">
		<div class="row">
			<div class="col-md-6">
			    <h3>Members</h3>
			    <div class="row">
			        <div class="col-md-6">
					    {% csrf_token %}
					    {{ form.non_field_errors }}
					    
					    <img src="{{ group.participant.get_image }}" width="150" height="150" alt="" />
		
				        <div class="form-group">
				            {{ form.title|label_with_classes:"control-label" }} 
				            {{ form.title|attr:"class:form-control" }}
			            </div>
			            <div id="form-errors" style="color:red;">{{ form.title.errors }}</div>
			            
			            <div class="form-group">
				            {{ form.description|label_with_classes:"control-label" }} 
				            {{ form.description|attr:"class:form-control" }}
			            </div>
			            <div id="form-errors" style="color:red;">{{ form.description.errors }}</div>
		
					    <input type="hidden" name="redirect-url" value="" />
					    <input type="submit" value="Submit" />
				    </div>
				    <div class="col-md-6">
					    {% for field in form %}
					    	{% if field.label == 'Neighborhood' or field.label == 'City' or field.label == 'Phone number' or field.label == 'Phone type' or field.label == 'Email' or field.label == 'Website' %}
			                {% include 'blocks/formgroup.html' %}
			                {% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
			
			<div class="col-md-6">
			    <h3>Members</h3>
			    <strong>Awaiting Approval:</strong><br>
			    {% for participant in awaitingApproval %}
			        {% include 'blocks/participantgroup.html' %}
			    {% empty %}
			        <em>None</em>
			    {% endfor %}
			    <hr>
			    <strong>Current Members:</strong><br>
			    {% for participant in currentMembers %}
			        {% include 'blocks/participantgroup.html' %}
			    {% empty %}
			        <em>None</em>
			    {% endfor %}
			    <br>
			    <button type="button" class="btn btn-primary">Invite More People</button>
			</div>
		</div>
	</form>
{% endblock %}

account/templates/personal_info.html
{% extends "base.html" %}
{% load app_filters %}
{% load widget_tweaks %}<!-- https://pypi.python.org/pypi/django-widget-tweaks -->
{% load staticfiles %}

{% block content %}

{% include "js/personal_info.html" %}
{% include "modals/upload_tool.html" %}	

    <div class="container-fluid">
        {% include "blocks/create-account-header.html" %}
	    <form action="{{ callback }}" method="post" id="personal-info-form">
	        <div style="display:none;">
	            <!-- Account Info form is hidden here -->
	        	{% for field in hiddenForm %}	
			        <div class="form-group">
				        {{ field.errors }}
			            {{ field|label_with_classes:"control-label" }} 
			            {{ field|attr:"class:form-control" }}
		            </div>
			    {% endfor %}
			    <div class="form-group">
			        {{ form.image.errors }}
		            {{ form.image|label_with_classes:"control-label" }} 
		            {{ form.image|attr:"class:form-control"|attr:"readonly" }}
	            </div>
	            <div class="form-group">
			        {{ form.thumb.errors }}
		            {{ form.thumb|label_with_classes:"control-label" }} 
		            {{ form.thumb|attr:"class:form-control"|attr:"readonly" }}
	            </div>
	        </div>
			<div class="row">
				<div class="col-md-4">
					    {% csrf_token %}
				        <div class="form-group">
					        {{ form.full_address.errors }}
				            {{ form.full_address|label_with_classes:"control-label" }} 
				            {{ form.full_address|attr:"class:form-control"|attr:"readonly" }}
			            </div>
			            <div class="form-group">
					        {{ form.street.errors }}
				            {{ form.street|label_with_classes:"control-label" }} 
				            {{ form.street|attr:"class:form-control" }}
			            </div>
			            <div class="form-group">
					        {{ form.city.errors }}
				            {{ form.city|label_with_classes:"control-label" }} 
				            {{ form.city|attr:"class:form-control" }}
			            </div>
			            <div class="form-group">
					        {{ form.neighborhood.errors }}
				            {{ form.neighborhood|label_with_classes:"control-label" }} 
				            {{ form.neighborhood|attr:"class:form-control" }}
			            </div>
				</div>
				<div class="col-md-4">
						<img id="user-pic" src="{% static "img/generic-user.png" %}" alt="User Pic" width="150" height="150" />
						<button type="button" class="btn btn-info" data-toggle="modal" data-target="#upload-pic-modal">
							Upload Picture
						</button>
				        <div class="checkbox">
					        {{ form.share_email.errors }}
				             
				            {{ form.share_email }}
				            {{ form.share_email.label_tag|remove_colon }}
			            </div>
			            <div class="checkbox">
					        {{ form.share_phone.errors }}
				             
				            {{ form.share_phone }}
				            {{ form.share_phone.label_tag|remove_colon }}
			            </div>
			            <div id="phone-info">
			            	<div class="form-group">
						        {{ form.phone_number.errors }}
					            {{ form.phone_number|label_with_classes:"control-label" }} 
					            {{ form.phone_number|attr:"class:form-control" }}
				            </div>
				            <div class="form-group">
						        {{ form.phone_type.errors }}
					            {{ form.phone_type|label_with_classes:"control-label" }} 
					            {{ form.phone_type|attr:"class:form-control" }}
				            </div>
			            </div>
					    
					    <input type="submit" value="Submit" />
				</div>
				<div class="col-md-4">
					<h3>Shared with Everyone</h3>
					    <img id="shared-user-pic" src="{% static "img/generic-user.png" %}" alt="User Pic" width="55" height="55" />
					    <span id="shared-first-name"></span> <span id="shared-last-name"></span><br />
					    <span id="shared-street"></span> (<span id="shared-neighborhood"></span>)
					<hr>
					<h3>Shared Only with Friends</h3>
					<div id="shared-email-show">
						<strong>Email: </strong> <span id="shared-email"></span>
					</div>
					<div id="shared-phone-show">
						<strong>Phone: </strong> <span id="shared-phone"></span> <span id="shared-phone-type"></span>
					</div>
				</div>
			</div>
		</form>
	</div>




{% endblock %}