account/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'account_info/', views.account_info, name='account_info'),
    url(r'address/', views.address, name='address'),
    url(r'personal_info/', views.personal_info, name='personal_info'),
    url(r'confirmation/', views.confirmation, name='confirmation'),
    
    url(r'setup_facebook_login/', views.setup_facebook_login, name='setup_facebook_login'),
    
    #url(r'new_facebook_account/', views.new_facebook_account, name='new_facebook_account'),
    
    url(r'create_group/', views.create_group, name='create_group'),
    url(r'edit_group/([0-9]*)', views.edit_group, name='edit_group'),
    url(r'delete_group/', views.delete_group, name='delete_group'),
    
    url(r'account/', views.account, name='account'),
    
    url(r'upload_image/', views.upload_image, name='upload_image'),
    url(r'view/([0-9]*)', views.view, name='view'),
    url(r'unsubscribe/', views.unsubscribe, name='unsubscribe'),
    url(r'unsubscribe_confirm/', views.unsubscribe_confirm, name='unsubscribe_confirm'),
    
]

pm/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'messages/([0-9]*)', views.messages, name='messages'),
    url(r'message_list', views.message_list, name='message_list'),
]

sharing/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^share_item/', views.share_item, name='share_item'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
    url(r'^items/', views.items, name='items'),
    url(r'^my_items/', views.my_items, name='my_items'),
    url(r'^my_share_lists/', views.my_share_lists, name='my_share_lists'),
    url(r'^item/([0-9]*)', views.item, name='item'),
    url(r'^public_item/([a-zA-Z0-9]*)', views.public_item, name='public_item'),
    url(r'^make_item_public/', views.make_item_public, name='make_item_public'),
    url(r'^edit_item/([0-9]*)', views.edit_item, name='edit_item'),
    url(r'^edit_sharelist/([0-9]*)', views.edit_sharelist, name='edit_sharelist'),
    url(r'^delete_sharelist', views.delete_sharelist, name='delete_sharelist'),
    url(r'^delete_item', views.delete_item, name='delete_item'),
    url(r'^quick_share', views.quick_share, name='quick_share'),
    url(r'^new_group_action/([0-9]*)', views.new_group_action, name='new_group_action'),
]

villagebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'main.views.custom_404'
handler500 = 'main.views.custom_500'
handler403 = 'main.views.custom_403'

urlpatterns = [
    #direct links to views
    url(r'^login/', 'main.views.login_view', name='login'),
    url(r'^facebook_test/', 'main.views.facebook_test', name='facebook_test'),
    url(r'^facebook_login_test/', 'main.views.facebook_login_test', name='facebook_login_test'),
    url(r'^logout/', 'main.views.logout_view', name='logout'),
    url(r'^hide_me/', 'main.views.hide_me', name='hide_me'),
    url(r'^request_reset_password/', 'main.views.request_reset_password', name='request_reset_password'),
    url(r'^reset_password/([a-zA-Z0-9]*)', 'main.views.reset_password', name='reset_password'),
    url(r'^info$', 'main.views.info', name='info'),
    
    #note: pages in main do not have a namespace 
    url(r'^$', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^relationships/', include('relationships.urls', namespace="relationships")),
    url(r'^alerts/', include('alerts.urls', namespace="alerts")),
    url(r'^requests/', include('requests.urls', namespace="requests")),
    url(r'^pm/', include('pm.urls', namespace="pm")),
    url(r'^sharing/', include('sharing.urls', namespace="sharing")),
    
    
]

sharing/models.py
import collections

from django.core.urlresolvers import reverse
from django.db import models

from account.models import Member, Participant, Group

# computer value, display value
# !! these should all be unique names even across item types
stuffKeywords = [
    ['tools', 'tools'],
    ['electronics/appliances', 'electronics/appliances'],
    ['sports/games', 'sports/games'],
    ['outdoor/camping', 'outdoor/camping'],
    ['kids', 'kids'],
    ['art/crafts', 'art/crafts'],
    ['materials/chemicals', 'materials/chemicals'],
    ['music/media', 'music/media'],
    ['food', 'food'],
    ['other stuff', 'other stuff'],
]
spaceKeywords = [
    ['living/sleeping space', 'living/sleeping space'],
    ['event space', 'event space'],
    ['meeting space', 'meeting space'],
    ['garden space', 'garden space'],
    ['storage space', 'storage space'],
    ['play area', 'play area'],
    ['kitchen/dining space', 'kitchen/dining space'],
    ['other space', 'other space'],            
]
laborKeywords = [
    ['home repair', 'home repair'],
    ['computer/technical', 'computer/technical'],
    ['child care', 'child care'],
    ['legal', 'legal'],
    ['creative', 'creative'],
    ['yard/gardening', 'yard/gardening'],
    ['other labor', 'other labor'],             
]
# computer value, display value, associated keywords
SHARE_CATEGORIES = [
    ['stuff', 'Stuff', stuffKeywords],
    ['space', 'Space', spaceKeywords],
    ['labor', 'Labor/Skills', laborKeywords],                                 
]



class Item(models.Model):
    SHARE_TYPES = (
        ('all_friends', 'all_friends'),
        ('share_list', 'share_list'),
        ('custom', 'custom'),
    )
    ITEM_TYPES = ()
    for category in SHARE_CATEGORIES:
        ITEM_TYPES = ITEM_TYPES + ((category[0], category[1]),)
    # print(ITEM_TYPES)
    sharer = models.ForeignKey(Member, on_delete=models.CASCADE)
    share_type = models.CharField(max_length=30, choices=SHARE_TYPES, db_index=True)
    share_date = models.DateTimeField(auto_now_add=True, db_index=True)
    type = models.CharField(max_length=30, choices=ITEM_TYPES, db_index=True)
    title = models.CharField(max_length=120, db_index=True)
    description = models.TextField(blank=True, null=True)
    image = models.CharField(max_length=30, blank=True, null=True)
    thumb = models.CharField(max_length=30, blank=True, null=True)
    to_borrow = models.BooleanField(default=True, db_index=True)
    to_keep = models.BooleanField(default=False, db_index=True)
    public = models.BooleanField(default=False, db_index=True)
    facebook_date = models.DateTimeField(db_index=True, blank=True, null=True)
    code = models.CharField(max_length=30, null=True, blank=True, db_index=True)
    # category = models.ForeignKey("Category", on_delete=models.CASCADE)
    sharelist = models.ForeignKey("ShareList", on_delete=models.CASCADE, null=True, blank=True)
    
   
    def get_public_link(self):
        return 'https://villagebuilder.net' + reverse('sharing:public_item', args=[self.code])
    
    def get_image(self):
        if self.image:
            return '/static/uploads/item_pics/' + self.image
        return '/static/img/generic-item.png'
    
    def get_thumb(self):
        if self.thumb:
            return '/static/uploads/item_pics/' + self.thumb
        return '/static/img/generic-item.png'
    
    def has_thumb(self):
        if self.thumb:
            return True
        return False
    
    
    
class ItemKeyword(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=60, db_index=True)
    
class ItemGroup(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    shared = models.BooleanField(default=True, db_index=True)

#class Category(models.Model):
#    name = models.CharField(max_length=60)
#    parent = models.ForeignKey("Category", on_delete=models.CASCADE, null=True, blank=True)
    
class ItemSharee(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    sharee = models.ForeignKey(Member, on_delete=models.CASCADE)
    
class ShareList(models.Model):
    name = models.CharField(max_length=60)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE)
    
class ShareListSharee(models.Model):
    shareList = models.ForeignKey("ShareList", on_delete=models.CASCADE)
    sharee = models.ForeignKey(Member, on_delete=models.CASCADE)
    
class SharingActionNeeded(models.Model):
    alertee = models.ForeignKey(Member, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, db_index=True) # new friend, new group
    subject = models.ForeignKey(Participant, on_delete=models.CASCADE)
    

    
    
    

sharing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import *




class ItemForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        # the sharingWith field has to be set dynamically
        participant = kwargs.pop('participant', None)
        shareLists = ShareList.objects.all().filter(owner=participant.member)
        shareListOptions = []
        if shareLists.count() != 0:
            for shareList in shareLists:
                shareListOptions.append([shareList.id, shareList.name])
        shareOptions = [
            ['all_friends', 'All Friends'],
            ['custom', 'Custom'],
        ]
        if len(shareListOptions) != 0:
            shareOptions.append(['Share Lists:', shareListOptions])
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields["sharingWith"] = forms.ChoiceField(choices=shareOptions)
        instance = kwargs.get('instance', None)
        if instance:
            if instance.share_type == 'share_list':
                self.fields["sharingWith"].initial = instance.sharelist.id
            else:
                self.fields["sharingWith"].initial = instance.share_type
    
    class Meta:
        model = Item
        fields = ['type','title', 'description', 'image', 'thumb', 'to_borrow', 'to_keep',]

    # sharingWith = forms.ChoiceField(choices=SHARE_OPTIONS)
    CREATE_SHARE_LIST = (
        ('no', 'No',),
        ('yes', 'Yes',), 
    )
    createShareList = forms.ChoiceField(widget=forms.RadioSelect, choices=CREATE_SHARE_LIST, initial='no')
    shareListName = forms.CharField(max_length=60, label="Share List Name", required=False)

class KeywordForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        setKeywords = kwargs.pop('setKeywords', None)
        super(KeywordForm, self).__init__(*args, **kwargs)
        for itemType in SHARE_CATEGORIES:
            fieldName = 'keywords_' + itemType[0]
            self.fields[fieldName] = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                             choices=itemType[2], required=False)  
            self.fields[fieldName].initial = setKeywords     


villagebuilder/templates/sharing/my_items.html
{% extends "core/bases/home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block subcontent %}


<script>

$(document).ready(function(){
	
	//facebook integration
	$.ajaxSetup({ cache: true });
	$.getScript('//connect.facebook.net/en_US/sdk.js', function(){
  		FB.init({
    		appId: '1184393148243808',
    		version: 'v2.4' // or v2.0, v2.1, v2.2, v2.3
  		});     
  		//$('#loginbutton,#feedbutton').removeAttr('disabled');
  		//FB.getLoginStatus(updateStatusCallback);
	});

	$('.btn-make-item-public').click(function() {
		id = $(this).attr('id').substring(21)
		var postData = {
			item_id : id
		}
		$.post("{% url 'sharing:make_item_public' %}", postData, function(data, status){
			if (status == 'success') {
	    		$('#item-public-link-' + data.id).val(data.link);
	    		$('#item-public-link-div-' + data.id).slideDown();
			}
	    });
	});
	
	$('.btn-share-on-facebook').click(function() {
		id = $(this).attr('id').substring(22)
		var postData = {
			item_id : id
		}
		$.post("{% url 'sharing:make_item_public' %}", postData, function(data, status){
			if (status == 'success') {
				FB.ui({
					method: 'share',
					href: data.link
		  		}, function(response){
		  			console.log(response);
		  		});
			}
	    });
	});

}); 

</script>






<div id="top-section">
	<div id="top-actions">
		<div class="btn-group">
			<a href="{% url 'sharing:share_item' %}?type=stuff" class="btn btn-success">Share Something</a>
			<a href="#" class="btn btn-success dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-caret-down"></i>&nbsp;</a>
			<ul class="dropdown-menu">
			    {% for category in shareCategories %}
				    <li>
				    	<a href="{% url 'sharing:share_item' %}?type={{ category.0 }}">
				    		<span style="display:inline-block; width: 200px;">Share {{ category.1 }}</span>
				    		<i class="fa fa-plus"></i>
				    	</a>
				    </li>
				{% endfor %}
				<li>
					<a href="{% url 'sharing:quick_share' %}">
						<span style="display:inline-block; width: 200px;">Quick Share Common Items</span>
						<i class="fa fa-list-ul"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<h2 id="top-title">Items Shared by You</h2>
</div>


<div class="row">
	<div class="col-md-12">
	   	{% if items.count > 0 %}
	   	<table class="table">
	   		<tr>
		   		<th class="text-warning">Your Shared Items</th>
		   		<th class="text-warning">Sharing With</th>
		   		<th class="text-warning">Actions</th>
	   		</tr>
		   	{% for item in items %}
		   		<tr>
		   			<td style="vertical-align:middle">
		   				{% include 'sharing/blocks/itemblock.html' %}
		   			</td>
		   			<td style="vertical-align:middle;font-size:0.9em;" class="text-muted">
		   				{% include 'sharing/blocks/sharing_scope.html' %}
		   			</td>
		   			<td style="vertical-align:middle">
			   			<a class="btn btn-sm btn-default" href="{% url 'sharing:item' item.id %}">View</a>
			    		<a class="btn btn-sm btn-warning" href="{% url 'sharing:edit_item' item.id %}"><i class="fa fa-pencil"></i> Edit</a>
			    		<button class="btn btn-sm btn-primary btn-share-on-facebook" id="btn-share-on-facebook-{{item.id}}">
			    			<i class="fa fa-facebook-official"></i> Share on Facebook
			    		</button>
			    		<button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#share-by-email-modal-{{item.id}}">
			    			<i class="fa fa-envelope"></i> Share by email
			    		</button>
		   			</td>
		   		</tr>
		   	{% endfor %}
	   	</table>
		{% else %}
		    <p>You are not sharing any items yet.</p>
		    <p>Use the 
		    <a href="{% url 'sharing:quick_share' %}">quick share common items tool</a>
			or share individual items on the 
			<a href="{% url 'sharing:share_item' %}?type=stuff">share something</a> page.</p>
		{% endif %}
	</div>
</div>

{% for item in items %}
	<div class="modal" id="share-by-email-modal-{{item.id}}">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
				    <h4 class="modal-title">Share by Email</h4>
				</div>
				<div class="modal-body">
					{% if item.public %}
						Use the following public link to share your item
						with friends who don't have VillageBuilder accounts:
						<br><br>
						
						<div class="form-group">
						    <input type="text" class="form-control" readonly
						    onclick="select()" value="{{ item.get_public_link }}" />
						    <span class="help-block">Click and CTRL-C to copy</span>
						</div>
					{% else %}
					    <p>
					        This will create a public link for your item that you can share with anyone,
					        whether they have a VillageBuilder account or not.
					    </p>
					    <button type="button" class="btn btn-default btn-make-item-public" 
					    	id="btn-make-item-public-{{item.id}}">Create link</button>
					    <br><br>
					    <div class="form-group" id="item-public-link-div-{{item.id}}" style="display:none;">
						    <input type="text" class="form-control" 
						    	id="item-public-link-{{item.id}}" readonly onclick="select()" />
						    <span class="help-block">Click and CTRL-C to copy</span>
						</div>
					{% endif %}
				  
				</div>
			</div>
		</div>
	</div>
{% endfor %}




{% endblock %}

villagebuilder/templates/sharing/share_item.html
{% extends "core/bases/home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block subcontent %}

<script type="text/javascript">

	function updatePageAfterImageUpload(data) {
		console.log(data)
		$('#id_image').val(data.image.file);
		$('#id_thumb').val(data.thumb.file);
		$("#item-pic").attr("src", data.image.path);
	}
	
	var dataToAccompanyImageUpload = {}
	var imageUploadUrl = '{% url 'sharing:upload_image' %}'
	
	var defaultImage = '{% static "img/generic-item.png" %}';
	
	


    
</script>

{% include 'core/modals/upload_tool.html' %}

<script type="text/javascript">

$(document).ready(function(){
	
	
	
	$('#id_sharingWith').change(function() {
		var value = $(this).val()
		if (value == 'custom') {
			$('#custom-friends-form').slideDown();
		} else {
			$('#custom-friends-form').hide();
		}
		$('.share-list').hide();
		if (value != 'all_friends' && value != 'all_friends_groups' && value != 'custom') {
			$('#share-list-' + value).slideDown();
		}
	}).trigger("change");
	
	$('#fake-submit').click(function() {
		if ($('#id_sharingWith').val() == 'custom') {
			$('#save-sharelist-modal').modal('show');
		} else {
			$('#main-form').submit();
		}
	});
	
	$('input[name=createShareList]').click(function() {
		if($('#id_createShareList_1').is(':checked')) {
			$('#new-share-list-name').slideDown();
		} else {
			$('#new-share-list-name').slideUp();
		}
		if ( $('#id_shareListName').val() == '' && $('#id_createShareList_1').is(':checked')) {
    		$('#continue-submission').prop("disabled",true);
    	} else {
    		$('#continue-submission').prop("disabled",false);
    	}
	});
	
	if($('#id_createShareList_1').is(':checked')) {
		$('#new-share-list-name').show();
	}
	
	$('#id_shareListName').on("change keyup paste", function() {
    	if ( $(this).val() == '' && $('#id_createShareList_1').is(':checked')) {
    		$('#continue-submission').prop("disabled",true);
    	} else {
    		$('#continue-submission').prop("disabled",false);
    	}
    }).trigger("change");
	
	$('#id_type').change(function() {
		//show or hide keyword options for item
		var keywordBlockId = '#keywords_' + $(this).val().toLowerCase();
		$('.keyword_block').hide();
		$(keywordBlockId).slideDown();
		//show or hide type-specific options
		if ( $(this).val().toLowerCase() == 'stuff' ) {
			$('#stuff-special-options').slideDown();
		} else {
			$('#stuff-special-options').hide();
		}
	}).trigger("change");
	
	$('#delete-image').click(function() {
		$('#id_image').val('');
		$('#id_thumb').val('');
		$("#item-pic").attr("src", "{% static 'img/generic-item.png' %}");
	});


}); 


</script>


<div id="top-section">
	<div id="top-actions">
		{% if item %}
		    <button type="button" id="fake-submit" class="btn btn-success">Save Changes</button>&nbsp;
		    <a href="{% url 'sharing:item' item.id %}" class="btn btn-default">Exit Without Changing</a>&nbsp;
		    <a href="#" data-toggle="modal" data-target="#delete-item-modal" class="btn btn-danger">
		        <i class="fa fa-trash-o"></i> Delete Item
		    </a>
		    
		{% else %}
			<span class="text-warning">
		    	<i class="fa fa-exclamation-triangle"></i>
		    	By sharing an item, you agree to our 
		    	<a href="#" data-toggle="modal" data-target="#sharing-policies-modal">sharing policies</a>.
		    </span>
		    &nbsp;&nbsp;
		    <button type="button" id="fake-submit" class="btn btn-success">
		        Share Item <i class="fa fa-share-alt"></i>
		    </button>
		{% endif %}
	</div>
	<h2 id="top-title">Share Something</h2>
</div>

<form action="{{ callback }}" method="post" id="main-form">
<div style="display:none;">
	{% csrf_token %}
	{{ itemForm.image }}
	{{ itemForm.thumb }}
</div>
	<div class="row">
	    <div class="col-md-4">
		    {{ itemForm.non_field_errors }}
		    <div class="form-group">
	            {{ itemForm.title|label_with_classes:"control-label" }} 
	            {{ itemForm.title|attr:"class:form-control" }}
            </div>
            <div id="form-errors" class="text-danger">{{ itemForm.title.errors }}</div>
		    <div class="form-group">
	            {{ itemForm.type|label_with_classes:"control-label" }} 
	            {{ itemForm.type|attr:"class:form-control" }}
            </div>
            <div style="display:none;" id="stuff-special-options">
	            <label class="control-label">Options: &nbsp;&nbsp;
		                <span class="text-muted">(select any that apply or other)</span></label>
	            <div class="checkbox">
					<label>
		            	{{ itemForm.to_borrow }} {{ itemForm.to_borrow.label }}
		            </label>&nbsp;&nbsp;&nbsp;&nbsp;
		            <label>
		            	{{ itemForm.to_keep }} {{ itemForm.to_keep.label }}
		            </label> 
		        </div>
		        <hr>
		    </div>
            <div id="form-errors" class="text-danger">{{ itemForm.type.errors }}</div>
            {% for field in keywordForm %}
                <div id="{{ field.html_name }}" class="keyword_block" style="display:none;">
	                <label class="control-label">Categories: &nbsp;&nbsp;
	                <span class="text-muted">(select any that apply or other)</span></label>
		            <div class="checkbox" style="overflow: hidden;">
			            {% for checkbox in field %}
			                <div class="well well-sm" style="float:left;margin-right:10px;">
				            	{{ checkbox }}
				            </div>
				        {% endfor %}
			        </div>
		        </div>
		    {% endfor %}
		</div>
		<div class="col-md-4">
		    <div>
		        <label class="control-label">Picture:</label><br>
		        <img id="item-pic" src="{{ itemImage  }}" 
					        alt="User Pic" width="150" height="150"
					        style="margin-right:10px;margin-bottom:10px;float:left;" />
				<div style="padding-top:20px;">
					<button type="button" class="btn btn-info" data-toggle="modal" data-target="#upload-pic-modal">
						Upload Picture
					</button>
					{% if item and item.has_thumb %}
					    <button type="button" class="btn btn-warning" id="delete-image" style="margin: 10px 0;">
							Delete Picture
						</button>
					{% endif %}
				</div>
			</div>
			<hr style="clear:both;">
            <div class="form-group">
	            {{ itemForm.description|label_with_classes:"control-label" }} 
	            {{ itemForm.description|attr:"class:form-control" }}
            </div>
            <div id="form-errors" class="text-danger">{{ itemForm.description.errors }}</div>
        </div>
        <div class="col-md-4">
        	<h4>Share With Groups</h4>
		    {% for participant in groups %}
		        <div>
		        	<div style="padding:0 0 10px 30px;">
		        		{% if participant.id in shareeGroups or not item %}
		        			<input type="checkbox" name="groups[]" value="{{participant.id}}" checked="checked" />
		        			{{ participant.name }}
		        		{% else %}
		        		    <input type="checkbox" name="groups[]" value="{{participant.id}}" />
		        		    {{ participant.name }}
		        		{% endif %}
		        	</div>
		        </div>		
		    {% endfor %}
	        <div class="form-group">
	            <h4>Share With Friends</h4>
	            {{ itemForm.sharingWith|attr:"class:form-control" }}
            </div>
            <div id="form-errors" class="text-danger">{{ itemForm.sharingWith.errors }}</div>
            {% for shareList in shareLists %}
	            <div class="well share-list" id="share-list-{{ shareList.id }}" style="display:none;">
	                {% for shareListSharee in shareList.sharelistsharee_set.all %}
	                    {% with participant=shareListSharee.sharee %}
	                        {% include "core/blocks/participantgroup_fromobjects.html" %}
	                    {% endwith %}
	                {% endfor %}
	            </div>
            {% endfor %}
		    <div class="well" id="custom-friends-form" style="display:none;margin:0 10px;">
		        <div style="height:300px;overflow-y:auto;border:#C0C0C0 solid 1px;padding-top:5px;">
		        	<div>
					    {% for participant in friends %}
			        			<div class="col-sm-9">
					        		{% include "core/blocks/participantgroup_noactions.html" %}
					        	</div>
					        	<div class="col-sm-3" style="padding-top:20px;">
					        		{% if item.share_type == 'custom' and participant.id in sharees %}
					        			<input type="checkbox" name="custom_list[]" value="{{participant.id}}" checked="checked" />
					        			include
					        		{% else %}
					        		    <input type="checkbox" name="custom_list[]" value="{{participant.id}}" />
					        		    include
					        		{% endif %}
					        </div>		
					    {% endfor %}
					</div>
			    </div>
		    </div>
		</div>
	</div>

	<div class="modal" id="save-sharelist-modal">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
	        <h4 class="modal-title">Save Share List?</h4>
	      </div>
	      <div class="modal-body">
	        <p>You are sharing this item with a custom list of people.  Would you like to save these people
	        in a Share List that you can reuse in the future?</p>
	        {% for radio in itemForm.createShareList %}
	            <div class="radio">
	                {{ radio }}
	            </div>
	        {% endfor %}
	        <div class="form-group" id="new-share-list-name" style="display:none;">
			  {{ itemForm.shareListName|label_with_classes:"control-label" }}
			  <input class="form-control" id="{{ itemForm.shareListName.id_for_label }}" 
			          name="{{ itemForm.shareListName.html_name }}"
			          placeholder="ex: close friends, neighbors, friends with kids, woodworking buddies" type="text">
			</div>
	      </div>
	      <div class="modal-footer">
	        <button type="submit" class="btn btn-primary" id="continue-submission">Continue</button>
	      </div>
	    </div>
	  </div>
	</div>
</form>

<div class="modal" id="sharing-policies-modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h4 class="modal-title">VillageBuilder Sharing Policies</h4>
      </div>
      <div class="modal-body">
        {% include 'boilerplate/minimizing_risk.html' %}
        <br>
        {% include 'boilerplate/solicitation.html' %}
        <br>
        {% include 'boilerplate/liability.html' %}
        <br>
        {% include 'boilerplate/termination.html' %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="delete-item-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
        <h4 class="modal-title">Delete Item</h4>
      </div>
      <div class="modal-body">
        Do you really want to delete the item "{{ item.title }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'sharing:delete_item' %}">
        	{% csrf_token %}
        	<input type="hidden" name="item_id" value="{{ item.id }}" />
        	<button type="submit" class="btn btn-danger">Delete Item</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}