account/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'account_info/', views.account_info, name='account_info'),
    url(r'address/', views.address, name='address'),
    url(r'personal_info/', views.personal_info, name='personal_info'),
    url(r'confirmation/', views.confirmation, name='confirmation'),
    
    url(r'setup_facebook_login/', views.setup_facebook_login, name='setup_facebook_login'),
    
    #url(r'new_facebook_account/', views.new_facebook_account, name='new_facebook_account'),
    
    url(r'create_group/', views.create_group, name='create_group'),
    url(r'edit_group/([0-9]*)', views.edit_group, name='edit_group'),
    url(r'delete_group/', views.delete_group, name='delete_group'),
    
    url(r'account/', views.account, name='account'),
    
    url(r'upload_image/', views.upload_image, name='upload_image'),
    url(r'view/([0-9]*)', views.view, name='view'),
    url(r'unsubscribe/', views.unsubscribe, name='unsubscribe'),
    url(r'unsubscribe_confirm/', views.unsubscribe_confirm, name='unsubscribe_confirm'),
    
]

main/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

pm/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'messages/([0-9]*)', views.messages, name='messages'),
    url(r'message_list', views.message_list, name='message_list'),
]

relationships/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'add-friend/', views.add_friend, name='add-friend'),
    url(r'create-guest/', views.create_guest, name='create-guest'),
    url(r'remove-friend/', views.remove_friend, name='remove-friend'),
    url(r'add-guest-friend/', views.add_guest_friend, name='add-guest-friend'),
    url(r'remove-guest-friend/', views.remove_guest_friend, name='remove-guest-friend'),
    url(r'relationships/', views.relationships, name='relationships'),
    url(r'participant_search/', views.participant_search, name='participant_search'),
    url(r'email_search/', views.email_search, name='email_search'),
    
    url(r'friend_suggestions/', views.friend_suggestions, name='friend_suggestions'),
    
    url(r'^join_group/', views.join_group, name='join_group'),
    url(r'^unjoin_group/', views.unjoin_group, name='unjoin_group'),
    url(r'^add_to_group/', views.add_to_group, name='add_to_group'),
    url(r'^remove_from_group/', views.remove_from_group, name='remove_from_group'),
    url(r'^add_group_members/', views.add_group_members, name='add_group_members'),
]

villagebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'main.views.custom_404'
handler500 = 'main.views.custom_500'
handler403 = 'main.views.custom_403'

urlpatterns = [
    #direct links to views
    url(r'^login/', 'main.views.login_view', name='login'),
    url(r'^facebook_test/', 'main.views.facebook_test', name='facebook_test'),
    url(r'^facebook_login_test/', 'main.views.facebook_login_test', name='facebook_login_test'),
    url(r'^logout/', 'main.views.logout_view', name='logout'),
    url(r'^hide_me/', 'main.views.hide_me', name='hide_me'),
    url(r'^request_reset_password/', 'main.views.request_reset_password', name='request_reset_password'),
    url(r'^reset_password/([a-zA-Z0-9]*)', 'main.views.reset_password', name='reset_password'),
    url(r'^info$', 'main.views.info', name='info'),
    
    #note: pages in main do not have a namespace 
    url(r'^$', include('main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^relationships/', include('relationships.urls', namespace="relationships")),
    url(r'^alerts/', include('alerts.urls', namespace="alerts")),
    url(r'^requests/', include('requests.urls', namespace="requests")),
    url(r'^pm/', include('pm.urls', namespace="pm")),
    url(r'^sharing/', include('sharing.urls', namespace="sharing")),
    
    
]

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class RequestResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=120)
    
    def clean(self):
        cleaned_data = super(RequestResetPasswordForm, self).clean()
        email = cleaned_data.get("email")
        users = User.objects.all().filter(username=email)
        if users.count() == 0:
            self.add_error('email', 'That email was not found in our system.')
            
class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(max_length=128, widget=forms.PasswordInput)
    resubmit_password = forms.CharField(max_length=128, widget=forms.PasswordInput)
        
    def clean(self):
        cleaned_data = super(ResetPasswordForm, self).clean()
        new_password = cleaned_data.get("new_password")
        resubmit_password = cleaned_data.get("resubmit_password")
        if new_password != resubmit_password:
            self.add_error('resubmit_password', 'Password values didn\'t match.')
            
            
            
            
            
            
            
            

main/views.py
#-----------------------------------------------------------------
# all this crap is from django.contrib.auth.views
# much of it is needed to make login view work
import warnings

from django.conf import settings
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.deprecation import RemovedInDjango20Warning
from django.utils.encoding import force_text
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.utils.six.moves.urllib.parse import urlparse, urlunparse
from django.utils.translation import ugettext as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

#-----------------------------------------------------------------



from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.core.mail import send_mail
from django.db import transaction

from account.helpers import *
from main.helpers import *
from relationships.helpers import *
from alerts.helpers import *
from requests.helpers import *
from email_system.helpers import *
from sharing.models import SHARE_CATEGORIES
from sharing.helpers import *
from account.forms import AccountInfoForm

from .forms import RequestResetPasswordForm, ResetPasswordForm

def custom_404(request):
    context = {}
    return render(request, 'core/404.html', context)

def custom_500(request):
    context = {}
    return render(request, 'core/500.html', context)

def custom_403(request):
    context = {}
    return render(request, 'core/403.html', context)

def facebook_test(request):
    context = {}
    return render(request, 'core/facebook_test.html', context)

def facebook_login_test(request):
    context = {
        'myform' : AccountInfoForm()
    }
    return render(request, 'core/facebook_login_test.html', context)

@login_required
def home(request):
    user = request.user
    currentParticipant = Participant.objects.get(user=user, type='member')
    requestList = getRequestList(currentParticipant, 0, 10)
    totalCount = requestList['total_count']
    if totalCount > 10:
        moreRequests = True
    else:
        moreRequests = False
    items = getItemsForParticipant(currentParticipant)
    recentItems = items[:5]
    shareCategories = getCategoriesWithCounts(items)
    # print(shareCategories)
    totalSharedWithYou = 0
    # print(shareCategories)
    for category in shareCategories:
        totalSharedWithYou = totalSharedWithYou + category[3]
    # does this person have any friends? (also need to exclude admin)
    relationships = getRelations(currentParticipant, currentParticipant, relationshipTypes=[
        RelationshipTypes.FRIENDS,
        RelationshipTypes.REQUEST_SENT, 
        RelationshipTypes.GROUP_MEMBER,
        RelationshipTypes.GROUP_MEMBER_REQUESTED,                                                                              
    ])
    relationshipCount = len(relationships)
    hasRelationshipActivity = doesUserHaveRelationshipActivity(currentParticipant)
    if Item.objects.filter(sharer=currentParticipant.member).count() == 0:
        hasSharedSomething = False
    else:
        hasSharedSomething = True
    context = {
            'current' : getCurrentUser(request),
            'peopleNearYou' : getPeopleNearYou(currentParticipant),
            'friendsOfFriends' : getFriendsOfFriends(currentParticipant),
            'RelationshipTypes' : RelationshipTypes,
            'requests' : requestList['requests'],
            'moreRequests' : moreRequests,
            'maxRequest' : 10,
            'shareCategories' : shareCategories,
            'totalSharedWithYou' : totalSharedWithYou,
            'recentItems' : recentItems,
            'hasRelationshipActivity' : hasRelationshipActivity,
            'hasSharedSomething' : hasSharedSomething,
            'actions' : getSharingActions(currentParticipant.member)
        }
    return render(request, 'core/home.html', context)

def logout_view(request):
    logout(request)
    return redirect('login')

def info(request):
    context = {}
    return render(request, 'core/boilerplate.html', context)

def test_view(request):
    return HttpResponse("It worked!")

@csrf_protect
@transaction.atomic
def reset_password(request, code):
    successMessage = ''
    errorMessage = ''
    members = Member.objects.all().filter(code=code)
    if members.count() != 1 or not code:
        return redirect('login')
    member = members[0]
    user = member.participant.user
    if request.method == "POST":
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            user.set_password(form.cleaned_data['new_password'])
            user.save()
            member.code = ''
            member.save()
            successMessage = 'Password Changed.  You can now <a href="' + reverse('login') + '">login</a>.'
    else:
        form = ResetPasswordForm()
    context = {
        'code' : code,
        'successMessage' : successMessage,
        'errorMessage' : errorMessage,
        'form' : form,
        'member' : member,
    }
    return render(request, 'core/reset_password.html', context)

@csrf_protect
def request_reset_password(request):
    successMessage = ''
    errorMessage = ''
    if request.method == "POST":
        form = RequestResetPasswordForm(request.POST)
        if form.is_valid():
            # get user
            user = User.objects.get(username=form.cleaned_data['email'])
            member = Participant.objects.get(user=user, type='member').member
            member.code = createRandomString(60)
            member.save()
            result = email_forgot_password(request, member)
            if result:
                successMessage = 'An email has been sent to you.  Please check your junk mail folder if it doesn\'t arrive.'
            else:
                errorMessage = ('There was an error with our email system.  If the problem ' +
                    'persists, contact <a href="mailto:admin@villagebuilder.net">the VillageBuilder administrator</a>.')
    else:
        form = RequestResetPasswordForm()
    context = {
        'form' : form,
        'successMessage' : successMessage,
        'errorMessage' : errorMessage,
    }
    return render(request, 'core/request_reset_password.html', context)

def hide_me(request):
    '''This will put a cookie on your browser that hides you from google analytics for 2 years.'''
    return render(request, 'core/hide_me.html', {})

@sensitive_post_parameters()
@csrf_protect
@never_cache
def login_view(request, template_name='core/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    This was copied and modified from django.contrib.auth.views.py.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)
    
    createAccountForm = AccountInfoForm(initial={
            'email': ifkeyset(request.session, 'email'),
            'first_name': ifkeyset(request.session, 'first_name'),
            'last_name': ifkeyset(request.session, 'last_name'),
        })

    context = {
        'form': form,
        'createAccountForm' : createAccountForm,
        'facebook_login_form' : AccountInfoForm(),
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)

main/templates/home.html
{% extends "home_base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block subcontent %}



    <div class="row">
    	<div class="col-md-3">
			<div class="form-group">
				  <div class="input-group">
				      <input class="form-control" type="text" placeholder="Search items shared with you">
				      <span class="input-group-btn">
				          <button class="btn btn-default" type="button">Go</button>
				      </span>
				  </div>
			</div>
			<button class="btn btn-primary btn-block">
			    Browse Items Shared with You >
			</button>
			<h3>Recent Listings</h3>
			<div class="list-group">
				<a href="#" class="list-group-item">
				    <h4 class="list-group-item-heading">List group item heading</h4>
				    <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
				</a>
				<a href="#" class="list-group-item">
				    <h4 class="list-group-item-heading">List group item heading</h4>
				    <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
				</a>
			</div>
    	</div>
    	<div class="col-md-6">
    	    <div class="float-right" style="margin-top: 5px">
		    	<div class="btn-group">
					<a href="#" class="btn btn-primary">Share Something</a>
					<a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-caret-down"></i>&nbsp;</a>
					<ul class="dropdown-menu">
						<li><a href="#">Stuff</a></li>
						<li><a href="#">Space</a></li>
						<li><a href="#">Meals</a></li>
						<li><a href="#">Skills/Labor</a></li>
						<li><a href="#">Activity</a></li>
					</ul>
				</div>
			</div>
			<ul class="nav nav-tabs">
				<li class="active" style="margin: 5px 5px -1px 0">
					<a href="" style="background-color:#F5F5F5">
						<span class="text-info">Request Something</span>
					</a>
				</li>
			</ul>
			<div class="tab-content" style="background-color:#F5F5F5; padding:0 7px 0 7px; border:solid 1px #DDDDDD; border-top: none">
				<br>
				<div class="form-group">
					<textarea class="form-control" rows="2" placeholder="Ask for something you need..."></textarea>
					<button type="submit" class="btn btn-default" style="margin-top: 5px">Post Request</button>
				</div> 
			</div>
			<hr>
			Here is where the feed is
		</div>
		<div class="col-md-3">
			<form action="{% url 'relationships:participant_search' %}" method="get">
				<div class="form-group">
					  <div class="input-group">
					      <input class="form-control" type="text" 
					          placeholder="Search for people or groups" 
					          name="participant-search-txt" />
					      <span class="input-group-btn">
					          <input class="btn btn-default" type="submit" id="participant-search-btn" value="Go" />
					      </span>
					  </div>
				</div>
			</form>
			<hr>
			<h3>People Near You</h3>
			<div class="list-group">
				{% for participant in peopleNearYou %}
				    {% include 'blocks/participantgroup.html' %}
				{% endfor %}
			</div>
			<h3>Friends of Friends</h3>
			<div class="list-group">
				{% for participant in friendsOfFriends %}
				    {% include 'blocks/participantgroup.html' %}
				{% endfor %}
			</div>
    	</div>
    </div>
{% endblock %}	





main/templates/home_base.html
{% extends "base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block content %}
	{% include "js/alerts.html" %}

    <nav class="navbar navbar-inverse">
	    <div class="container-fluid">
		    <div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'home' %}">VillageBuilder</a>
		    </div>
	
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'home' %}">Home</a></li>
					<li><a href="#">My Shared Items</a></li>
					<li><a href="{% url 'relationships:relationships' %}">Friends/Groups</a></li>
					<li><a href="#">Messages[0]</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="open-alerts">
						    Alerts <span id="alert-count"></span> <span class="caret"></span>
					    </a>
						<ul class="dropdown-menu widen" role="menu" id="alert-container">
							<li>&nbsp;&nbsp;<em>no alerts to show</em></li>
				        </ul>
					</li>
					<li><a href="#">User Guide</a></li>
					<li class="dropdown">
				</ul>
		        <ul class="nav navbar-nav navbar-right">
		            <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
			              <img class="current-user-pic" src="{{ current.member.get_user_pic }}" alt="my alt" width="25" height="25" />
			              {{current.user.get_full_name}} <span class="caret"></span>
			          </a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="{% url 'account:view' current.member.id %}"><i class="fa fa-user"></i> Your Profile</a></li>
			            <li><a href="{% url 'account:account' %}"><i class="fa fa-wrench"></i> Account Settings</a></li>
			            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
			            <li class="divider"></li>
			            <li>Groups</li>
			            {% for group in current.groups %}
			                <li><a href="{% url 'account:view' group.id %}"><i class="fa fa-users"></i> {{ group.title }}</a></li>
			            {% endfor %}
			            <li><a href="{% url 'account:create_group' %}"><i class="fa fa-plus"></i> Create New Group</a></li>
			          </ul>
			        </li>
		        </ul>
		    </div>
	    </div>
	</nav>
    <div class="container-fluid">
		{% block subcontent %}{% endblock %}
    </div>
{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% load app_filters %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
    	<div class="col-md-10 col-md-offset-1">
		    <div class="page-header">
		    	<h1>Village Builder</h1>
		    	<p class="lead">share resources with friends and neighbors</p>
		    </div>
	    </div>
    </div>
    <div class="row">
    	<div class="col-md-4 col-md-offset-1">
			<h3>reduces waste</h3>
			<p>Have power tools that spend most of their time gathering dust? Grow too many tomatoes this year? 
			VillageBuilder makes it easy to loan or share things you don't need or don't use often.</p>
			<h3>saves you money</h3>
			<p>People you share with can share back with you. Request a specific item or browse the entire inventory
			 of items your friends are sharing.</p>
			<h3>no fine print</h3>
			<p>VillageBuilder is free and gives you 100% control over what you share and who you share with. 
			We won't spam you or share your personal information, ever. Get started by creating an account today.</p>
    	</div>
    	<div class="col-md-4">
    	    <div class="panel panel-primary">
		  		<div class="panel-heading">
			    	<h3 class="panel-title">Login</h3>
			  	</div>
			  	<div class="panel-body">
			    	{% if form.errors %}
				    	<div class="alert alert-danger">
						    Unable to log in. Check your email and password.
						</div>
				    {% endif %}
				
				    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
				        {% csrf_token %}
				        <div class="form-group">
						    {{ form.username|label_with_classes:"control-label" }}
							{{ form.username|attr:"class:form-control" }}
							{{ form.password|label_with_classes:"control-label" }}
							{{ form.password|attr:"class:form-control" }}
						</div>
				        

				
				       <button type="submit" class="btn btn-primary" value="Login">Submit</button>
				       <input type="hidden" name="next" value="{{ next }}" />
				   </form>
				   <a href="{% url 'account:account_info' %}">Create Account</a> | <a href="">Forget Password</a>
			  	</div>
			</div>	
    	</div>
    </div>
{% endblock %}